on:
  # Trigger the workflow on push to master or any pull request
  # Ignore all tags
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "23 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 💣 Audit 💣

jobs:
  audit-check:
    runs-on: ubuntu-latest
    name: 💣 Audit 💣
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
      - name: 💣 Audit 💣
        id: audit
        uses: rustyhorde/audit-check@f4648bf40252eaebac4db1c36a69cff38269589e # v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deny: "warnings"
          create_issue: "true"
