on:
  # Trigger the workflow on push to master or any pull request
  # Ignore all tags
  push:
    branches:
      - master
      - legacy/*
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "43 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 🐛 Fuzz 🐛

jobs:
  fuzz-build:
    runs-on: ubuntu-latest
    name: 🐛 Build Fuzz Targets 🐛
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
      - name: 🦀 Nightly Toolchain 🦀
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: nightly
      - name: 💾 Cache 💾
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: "fuzz"
      - name: 📦 Install cargo-fuzz 📦
        uses: taiki-e/install-action@59012be0884e296ca2da49b530610e72c49039ad # v2.81.6
        with:
          tool: cargo-fuzz
      - name: 🐛 Build Fuzz Targets 🐛
        run: cargo +nightly fuzz build
