on:
  push:
    branches:
      - master
      - legacy/*
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "13 3 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 🦀 Rust 🦀

jobs:
  rustfmt:
    name: 📌 Formatting 📌
    uses: rustyhorde/workflows/.github/workflows/rustfmt.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main

  lints-linux:
    name: 🕳️ Clippy (Linux) 🕳️
    needs: rustfmt
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu

  lints-macos:
    name: 🕳️ Clippy (MacOS) 🕳️
    needs: rustfmt
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin

  lints-windows:
    name: 🕳️ Clippy (Windows) 🕳️
    needs: rustfmt
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: windows-latest
      channel: nightly
      target: x86_64-pc-windows-gnu

  test-linux:
    name: 🧪 Test (Linux) 🧪
    needs: lints-linux
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: ["1.85.1", "stable", "beta", "nightly"]
        target: [x86_64-unknown-linux-gnu]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}

  test-macos:
    name: 🧪 Test (MacOS) 🧪
    needs: lints-macos
    strategy:
      matrix:
        os: [macos-latest]
        channel: ["1.85.1", "stable", "beta", "nightly"]
        target: [apple-darwin]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}

  test-windows:
    name: 🧪 Test (Windows) 🧪
    needs: lints-windows
    strategy:
      matrix:
        os: [windows-latest]
        channel: ["1.85.1", "stable", "beta", "nightly"]
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}

  coverage-linux:
    name: 🧱 Coverage (Linux) 🧱
    needs: test-linux
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      lcov: true
      html: true
    secrets: inherit

  coverage-macos:
    name: 🧱 Coverage (MacOS) 🧱
    needs: test-macos
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin
      lcov: true
      html: true
    secrets: inherit

  coverage-windows:
    name: 🧱 Coverage (Wndows) 🧱
    needs: test-windows
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      os: windows-latest
      channel: nightly
      target: ${{ matrix.target }}
      lcov: true
      html: true
    secrets: inherit

  build_tier2:
    name: ☎️ Tier 2 ☎️
    needs: [coverage-linux, coverage-macos, coverage-windows]
    strategy:
      matrix:
        target:
          [
            aarch64-linux-android,
            aarch64-unknown-linux-gnu,
            aarch64-unknown-linux-musl,
            i686-unknown-linux-gnu,
            powerpc-unknown-linux-gnu,
            powerpc64-unknown-linux-gnu,
            riscv64gc-unknown-linux-gnu,
            sparc64-unknown-linux-gnu,
            wasm32-unknown-emscripten,
            x86_64-unknown-linux-musl,
          ]
    uses: rustyhorde/workflows/.github/workflows/build-tier2.yml@7a073ab416038755f63ff549d1331c9644d37cd7 # main
    with:
      target: ${{ matrix.target }}
